// The content of this file was generated by IBM Cloud
// No not modify it as it might get overridden

var IBMCloudEnv = require('ibm-cloud-env');
var serviceManager = require('./service-manager');
IBMCloudEnv.init();


module.exports = function(app){

      const KVTdbsrvc =  require( './service-dbkvt');
      const tdbs = new KVTdbsrvc();
      tdbs.createKvtDB( function( err, dbres){
          if (err) {
                console.log(err.message);
          } else {
                console.log( JSON.stringify(dbres) )
          }
      });


}